"""create ledger_events

Revision ID: b71324001085
Revises: 
Create Date: 2026-02-13 05:14:07.010145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b71324001085'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ledger_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_hash', sa.String(), nullable=False),
    sa.Column('previous_hash', sa.String(), nullable=False),
    sa.Column('merkle_root', sa.String(), nullable=False),
    sa.Column('signature', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ledger_events_id'), 'ledger_events', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ledger_events_id'), table_name='ledger_events')
    op.drop_table('ledger_events')
    # ### end Alembic commands ###
